module.exports = {
    alkUri : "http://localhost:4000",
    ELFOGAD : "JÓ Ez Így?",
    TORLES : "A kiválasztott tétel valóban törölhető?",
    szKonyvKerd : "Valóban a tétel számlakönyvelését akarja végrehajtani? ",
    szKonyvTorlKerd : "Valóban a számlakönyvelés törlését akarja végrehajtani? ",
    haKonyvKerd : "Valóban a tétel havi könyvelését akarja végrehajtani? ",
    haKonyvTorlKerd : "Valóban a havi könyvelés törlését akarja végrehajtani? ",
    okeWidth: "200",
    torlWidth: "480",
    szKonyvWidth: "650",
    szKonyvTorlWidth: "700",
    haKonyvWidth: "650",
    haKonyvTorlWidth: "680",
    okeSzoveg: "Tétel fölvitele/módosítása csak az 'IGEN' választására történik meg",
    torlSzoveg: "'IGEN' választására megtörténik a tétel végleges törlése. ",
    szKonyvSzoveg : "'IGEN' választására megtörténik a tétel számlakönyvelése. ",
    szKonyvTorlSzoveg : "'IGEN' választására megtörténik a számlakönyvelés törlése. ",
    haKonyvSzoveg : "'IGEN' választására megtörténik a tétel havi könyvelése. ",
    haKonyvTorlSzoveg : "'IGEN' választására megtörténik a havi könyvelés törlése. ",
    nemTorolheto: "Már megtörtént a tétel számlakönyvelése, így nem törölhető!",
    nemHavikonyv: "Még nem történt meg a tétel számlakönyvelése, így nem végezhető el!",
    nemModosithato: "Már megtörtént a tétel számlakönyvelése, így nem módosítható!",
};
